// Import Google fonts using Next.js built-in font loader
import { Outfit, Ovo } from "next/font/google";
// Import global CSS styles
import "./globals.css";

// Set up fonts with language subsets
const Outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const Ovo = Ovo({
  subsets: ["latin"],
  weight: ["400"],
});

// Metadata for the site
export const metadata = {
  title: "Portfolio 2025",
  description: "Generated by create next app",
};

// Root layout component that wraps all of the app
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${Outfit.className} ${Ovo.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
